apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-xhge
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-tanv-tenant/quarkus/devfile-sample-code-with-quarkus-xhge@sha256:76305ce0d79bb3faa551da324c60272f385c1c15eaf6f6204bc9112f2fa7f0c5
        name: my-java-quarkus
        resources: {}
status: {}
